name: "ci-workflow"

on:
  pull_request:
  push:
    branches:
      - main
      - develop
jobs:
  test:
    name: Deploy tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
         uses: actions/checkout@v2
         with:
          node-version: "17"

      - name: Install
        run: npm install
      - name: Build
        run: npm run build
